命令稿啟動於 2018年03月13日 下午 11:33:11
]0;~
[32mAlan@Alan-PC [33m~[0m
$ whoami; pwd
Alan
/home/Alan
]0;~
[32mAlan@Alan-PC [33m~[0m
$ git config -l
user.email=icearea123456@gmail.com
user.name=alan1200123
]0;~
[32mAlan@Alan-PC [33m~[0m
$ git con[K[Klone https://git [Khub.com/alan1200123/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;~
[32mAlan@Alan-PC [33m~[0m
$ exit

命令稿已於 2018年03月13日 下午 11:34:22
 完成