命令稿啟動於 2018年03月14日 上午 12:03:11
]0;~/lab1
[32mAlan@Alan-PC [33m~/lab1[0m
$ g++ lab1execution [C[1@-[1@o[1@ [C[C[C[C[C[C[C[C[C[C[C[C[C[Clab1.cpp
]0;~/lab1
[32mAlan@Alan-PC [33m~/lab1[0m
$ ./lab1execution l[K[K
insert an positive integer
30
15 46 23 70 35 106 53 160 80 40 20 10 5 16 8 4 2 1 ]0;~/lab1
[32mAlan@Alan-PC [33m~/lab1[0m
$ exit

命令稿已於 2018年03月14日 上午 12:04:15
 完成